language: python
python:
  - "3.4"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.2
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
before_install:
  - pip install -q django==$DJANGO_VERSION
install:
  - python setup.py develop
script:
  - python setup.py test
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=1.4.2